version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@wordpress/data"
    versions:
    - 4.26.2
    - 4.26.3
    - 4.26.5
    - 4.26.6
    - 4.26.7
    - 4.26.8
    - 4.27.0
    - 4.27.1
  - dependency-name: "@wordpress/api-fetch"
    versions:
    - 3.21.2
    - 3.21.3
    - 3.21.5
    - 3.22.0
    - 3.23.0
  - dependency-name: "@wordpress/block-editor"
    versions:
    - 5.2.10
    - 5.2.11
    - 5.2.2
    - 5.2.3
    - 5.2.5
    - 5.2.6
    - 5.2.7
    - 5.2.8
    - 5.2.9
    - 5.3.0
    - 5.3.1
  - dependency-name: "@wordpress/scripts"
    versions:
    - 13.0.0
    - 13.0.1
    - 13.0.2
    - 13.0.3
    - 14.0.0
    - 14.0.1
    - 14.1.0
  - dependency-name: "@wordpress/editor"
    versions:
    - 9.25.10
    - 9.25.11
    - 9.25.2
    - 9.25.3
    - 9.25.5
    - 9.25.6
    - 9.25.7
    - 9.25.8
    - 9.25.9
    - 9.26.0
    - 9.26.1
  - dependency-name: "@wordpress/blocks"
    versions:
    - 6.25.2
    - 7.0.0
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.5
    - 7.0.6
    - 8.0.0
    - 8.0.1
  - dependency-name: "@wordpress/env"
    versions:
    - 3.0.1
    - 3.0.2
    - 3.0.3
    - 4.0.0
    - 4.0.1
  - dependency-name: "@wordpress/icons"
    versions:
    - 2.10.0
    - 2.10.1
    - 2.9.0
    - 2.9.1
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@google/model-viewer"
    versions:
    - 1.4.1
    - 1.5.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
